[theme]
# Menggunakan tema dasar gelap Streamlit
base="dark" 
primaryColor="#1DB954"    # Hijau Spotify (Warna Tombol Primary, Slider, dll.)

# Warna Latar Belakang
backgroundColor="#191414"   # Hitam Pekat (Latar Belakang Utama, mengatasi kilatan putih)
secondaryBackgroundColor="#282828"  # Abu-abu Gelap (Sidebar/Latar Belakang Sekunder)

# Warna Teks
textColor="#F5F5DC"         # Beige (Warna Teks Utama)

# Font (Memastikan font default digunakan)
font="sans serif"